routes:
  crm_home:
    path: '/{reactRouting}'
    methods:
      - GET
    options:
      action: index
      controller: 'MicroCRM\Home\Controller\HomeController'
    defaults:
      reactRouting: ~